name       : python-markdown
version    : 3.1.1
release    : 5
source     :
    - https://github.com/Python-Markdown/markdown/archive/3.1.1.tar.gz : 6a6733d333f9115c2653e0ebd486eae368861c2834dd8e809d2781f6cb0fedea
license    : BSD-3-Clause
component  : programming.python
summary    : A Python implementation of Markdown
description: |
    This is a Python implementation of Markdown.
    It is almost completely compliant with the reference implementation, though there are a few known issues.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
