name       : python-markdown
version    : 3.4.1
release    : 11
source     :
    - https://github.com/Python-Markdown/markdown/archive/refs/tags/3.4.1.tar.gz : 308fc5215137d4c1a534dac29a209fc37588e6b964e1f4baab9e75fd709edd4e
homepage   : https://github.com/Python-Markdown/markdown
license    : BSD-3-Clause
component  : programming.python
summary    : A Python implementation of Markdown
description: |
    This is a Python implementation of Markdown. It is almost completely compliant with the reference implementation, though there are a few known issues.
builddeps  :
    - python-importlib-metadata # check
rundeps    :
    - python-importlib-metadata
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
