name       : python-markdown
version    : 3.3.4
release    : 8
source     :
    - https://github.com/Python-Markdown/markdown/archive/refs/tags/3.3.4.tar.gz : dcba963ea6d47d845aaa5d169911052985eec90d50267850c5c4c4fb4b05eff7
license    : BSD-3-Clause
component  : programming.python
summary    : A Python implementation of Markdown
description: |
    This is a Python implementation of Markdown.
    It is almost completely compliant with the reference implementation, though there are a few known issues.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
