name       : python-markdown
version    : 2.6.7
release    : 1
source     :
    - https://github.com/waylan/Python-Markdown/archive/2.6.7-final.tar.gz : 31287f97286d365d7be056e2388904a13c29926abc275e3d31a3e4035c67122b
license    : BSD-3-Clause
component  : programming.python
summary    : A Python implementation of Markdown
description: |
    This is a Python implementation of Markdown.
    It is almost completely compliant with the reference implementation, though there are a few known issues.
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
