name       : python-markdown
version    : '3.0'
release    : 3
source     :
    - https://github.com/Python-Markdown/markdown/archive/3.0.tar.gz : 524f39c20abd9ff42d38e93fdd9ccaf83629e793479203b9e0c86a3a0bcc7225
license    : BSD-3-Clause
component  : programming.python
summary    : A Python implementation of Markdown
description: |
    This is a Python implementation of Markdown.
    It is almost completely compliant with the reference implementation, though there are a few known issues.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python3_install
    for _f in "$installdir"/usr/bin/*; do
        mv -v "${_f}" "${_f}3"
    done
    %python_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        python setup.py test
    popd

    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py test
    popd
